[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
verbosity = 2
fuzz_runs = 1000

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
mainnet = "https://ethereum.publicnode.com"
sepolia = "https://ethereum-sepolia.publicnode.com"
worldchain = "https://worldchain-mainnet.g.alchemy.com/public"
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }